[package]
name = "nebula"
version = "0.1.0"
edition = "2021"

[dependencies]
cozo = { version = "0.7.6", features = ["storage-rocksdb"] }
sha2 = "0.10.8"
ulid = "1.1.3"
uuid = { version = "1.10.0", features = ["v4"] }
zenoh = "1.0.0-beta.4"
