[package]
name = "spaceport"
version = "0.1.0"
edition = "2021"

[dependencies]
cozo = { path = "../../cozo/cozo-core", features = ["storage-rocksdb"] }
tokio = { version = "1.40.0", features = ["full"] }
zenoh = "0.11.0"
nebula = {path = "../nebula"}