[package]
name = "celestia-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
scribe = "0.8.4"
serde = "1.0.210"
tui-textarea = { version = "0.7.0", features = ["search"] }
